name: Deploy pages

on: 
  push:
    branches:
      - main

jobs:
  deploy_pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./slidev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build --base liff-terraform-sample
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: slidev/dist
